/**
 * Weekly Agenda Seed & Utilities for IntegraMed
 * Provides realistic appointments distributed across Monday to Sunday
 * between 08:00 AM and 10:00 PM (30-min slots) matching real staff and patients.
 */

import { getStaffList } from './staffStorage.js';

/**
 * Computes Monday (YYYY-MM-DD) for any given reference date
 */
export function getMondayOfWeek(d = new Date()) {
  const date = new Date(d);
  const day = date.getDay(); // 0 is Sunday, 1 is Monday...
  const diff = date.getDate() - day + (day === 0 ? -6 : 1);
  const monday = new Date(date.setDate(diff));
  monday.setHours(0, 0, 0, 0);
  return monday;
}

/**
 * Returns formatted 'YYYY-MM-DD' string for given Date object
 */
export function formatDateKey(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const date = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${date}`;
}

/**
 * Generates sample encounters for the entire Monday-to-Sunday week
 * corresponding to the reference date.
 */
export function generateWeeklySampleEncounters(referenceDate = new Date()) {
  const monday = getMondayOfWeek(referenceDate);

  // Compute 7 days strings [Mon, Tue, Wed, Thu, Fri, Sat, Sun]
  const weekDates = [];
  for (let i = 0; i < 7; i++) {
    const cur = new Date(monday);
    cur.setDate(monday.getDate() + i);
    weekDates.push(formatDateKey(cur));
  }

  const [mon, tue, wed, thu, fri, sat, sun] = weekDates;

  return [
    // ==========================================
    // LUNES
    // ==========================================
    {
      id: `seed-mon-1-${mon}`,
      date: mon,
      time: '08:30',
      period: { start: `${mon}T08:30:00`, end: `${mon}T09:00:00` },
      patientId: 'mariana-silva',
      patientName: 'Mariana Silva Ruiz',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Control de Hipertensión y Asma',
      status: 'in_room',
      statusLabel: 'En sala',
      room: 'Consultorio 101',
      subject: { display: 'Mariana Silva Ruiz', reference: 'Patient/mariana-silva' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Control de Hipertensión y Asma' }],
      type: [{ text: 'Consulta de Especialidad' }]
    },
    {
      id: `seed-mon-2-${mon}`,
      date: mon,
      time: '10:00',
      period: { start: `${mon}T10:00:00`, end: `${mon}T10:30:00` },
      patientId: 'roberto-silva',
      patientName: 'Roberto Silva',
      practitionerName: 'Dr. Jesús Robledo',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Revisión post-operatoria de rodilla',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 102',
      subject: { display: 'Roberto Silva', reference: 'Patient/roberto-silva' },
      participant: [{ individual: { display: 'Dr. Jesús Robledo' } }],
      reasonCode: [{ text: 'Revisión post-operatoria de rodilla' }],
      type: [{ text: 'Revisión Quirúrgica' }]
    },
    {
      id: `seed-mon-3-${mon}`,
      date: mon,
      time: '11:30',
      period: { start: `${mon}T11:30:00`, end: `${mon}T12:00:00` },
      patientId: 'valeria-morales',
      patientName: 'Valeria Morales Gómez',
      practitionerName: 'Lic. Sofía Mendiola',
      practitionerSpecialty: 'Fisioterapia y Rehabilitación',
      reason: 'Terapia Bobath y rehabilitación neurológica',
      status: 'waiting',
      statusLabel: 'En espera',
      room: 'Cabina Bobath 2',
      subject: { display: 'Valeria Morales Gómez', reference: 'Patient/valeria-morales' },
      participant: [{ individual: { display: 'Lic. Sofía Mendiola' } }],
      reasonCode: [{ text: 'Terapia Bobath y rehabilitación neurológica' }],
      type: [{ text: 'Sesión de Fisioterapia' }]
    },
    {
      id: `seed-mon-4-${mon}`,
      date: mon,
      time: '15:00',
      period: { start: `${mon}T15:00:00`, end: `${mon}T15:30:00` },
      patientId: 'carlos-mendoza',
      patientName: 'Carlos Mendoza Sánchez',
      practitionerName: 'Dra. Beatriz Ramos',
      practitionerSpecialty: 'Cardiología Clínica',
      reason: 'Evaluación cardiológica y ecocardiograma',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 104',
      subject: { display: 'Carlos Mendoza Sánchez', reference: 'Patient/carlos-mendoza' },
      participant: [{ individual: { display: 'Dra. Beatriz Ramos' } }],
      reasonCode: [{ text: 'Evaluación cardiológica y ecocardiograma' }],
      type: [{ text: 'Consulta Cardiológica' }]
    },
    {
      id: `seed-mon-5-${mon}`,
      date: mon,
      time: '17:30',
      period: { start: `${mon}T17:30:00`, end: `${mon}T18:00:00` },
      patientId: 'lucia-fernandez',
      patientName: 'Lucía Fernández Peña',
      practitionerName: 'Dra. Elena Torres Morales',
      practitionerSpecialty: 'Neumología',
      reason: 'Espirometría y función respiratoria',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 105',
      subject: { display: 'Lucía Fernández Peña', reference: 'Patient/lucia-fernandez' },
      participant: [{ individual: { display: 'Dra. Elena Torres Morales' } }],
      reasonCode: [{ text: 'Espirometría y función respiratoria' }],
      type: [{ text: 'Prueba Respiratoria' }]
    },
    {
      id: `seed-mon-6-${mon}`,
      date: mon,
      time: '20:00',
      period: { start: `${mon}T20:00:00`, end: `${mon}T20:30:00` },
      patientId: 'jorge-salazar',
      patientName: 'Jorge Eduardo Salazar',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Valoración de dolor lumbar agudo',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 103',
      subject: { display: 'Jorge Eduardo Salazar', reference: 'Patient/jorge-salazar' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Valoración de dolor lumbar agudo' }],
      type: [{ text: 'Consulta Traumatológica' }]
    },

    // ==========================================
    // MARTES
    // ==========================================
    {
      id: `seed-tue-1-${tue}`,
      date: tue,
      time: '09:00',
      period: { start: `${tue}T09:00:00`, end: `${tue}T09:30:00` },
      patientId: 'ana-martinez',
      patientName: 'Ana Sofía Martínez',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Chequeo preventivo anual',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 101',
      subject: { display: 'Ana Sofía Martínez', reference: 'Patient/ana-martinez' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Chequeo preventivo anual' }],
      type: [{ text: 'Medicina Preventiva' }]
    },
    {
      id: `seed-tue-2-${tue}`,
      date: tue,
      time: '10:30',
      period: { start: `${tue}T10:30:00`, end: `${tue}T11:00:00` },
      patientId: 'miguel-torres',
      patientName: 'Miguel Ángel Torres',
      practitionerName: 'Lic. Carlos Treviño',
      practitionerSpecialty: 'Kinesiología Deportiva',
      reason: 'Descarga muscular y kinesiología deportiva',
      status: 'in_consultation',
      statusLabel: 'En consulta',
      room: 'Cabina Fisioterapia 1',
      subject: { display: 'Miguel Ángel Torres', reference: 'Patient/miguel-torres' },
      participant: [{ individual: { display: 'Lic. Carlos Treviño' } }],
      reasonCode: [{ text: 'Descarga muscular y kinesiología deportiva' }],
      type: [{ text: 'Kinesiología' }]
    },
    {
      id: `seed-tue-2b-${tue}`,
      date: tue,
      time: '10:30',
      period: { start: `${tue}T10:30:00`, end: `${tue}T11:00:00` },
      patientId: 'carlos-mendoza',
      patientName: 'Carlos Mendoza Sánchez',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Control de hipertensión y laboratorio',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 101',
      subject: { display: 'Carlos Mendoza Sánchez', reference: 'Patient/carlos-mendoza' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Control de hipertensión y laboratorio' }],
      type: [{ text: 'Medicina Interna' }]
    },
    {
      id: `seed-tue-3-${tue}`,
      date: tue,
      time: '13:00',
      period: { start: `${tue}T13:00:00`, end: `${tue}T13:30:00` },
      patientId: 'patricia-luna',
      patientName: 'Patricia Luna Cruz',
      practitionerName: 'Dra. Beatriz Ramos',
      practitionerSpecialty: 'Cardiología Clínica',
      reason: 'Control de arritmia y ajuste de dosis',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 104',
      subject: { display: 'Patricia Luna Cruz', reference: 'Patient/patricia-luna' },
      participant: [{ individual: { display: 'Dra. Beatriz Ramos' } }],
      reasonCode: [{ text: 'Control de arritmia y ajuste de dosis' }],
      type: [{ text: 'Seguimiento Cardiológico' }]
    },
    {
      id: `seed-tue-4-${tue}`,
      date: tue,
      time: '16:00',
      period: { start: `${tue}T16:00:00`, end: `${tue}T16:30:00` },
      patientId: 'mariana-silva',
      patientName: 'Mariana Silva Ruiz',
      practitionerName: 'Lic. Sofía Mendiola',
      practitionerSpecialty: 'Fisioterapia y Rehabilitación',
      reason: 'Sesión de fisioterapia cervical',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Cabina Bobath 2',
      subject: { display: 'Mariana Silva Ruiz', reference: 'Patient/mariana-silva' },
      participant: [{ individual: { display: 'Lic. Sofía Mendiola' } }],
      reasonCode: [{ text: 'Sesión de fisioterapia cervical' }],
      type: [{ text: 'Fisioterapia' }]
    },
    {
      id: `seed-tue-5-${tue}`,
      date: tue,
      time: '18:30',
      period: { start: `${tue}T18:30:00`, end: `${tue}T19:00:00` },
      patientId: 'roberto-silva',
      patientName: 'Roberto Silva',
      practitionerName: 'Dr. Jesús Robledo',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Curación y retiro de puntos quirúrgicos',
      status: 'waiting',
      statusLabel: 'En espera',
      room: 'Consultorio 102',
      subject: { display: 'Roberto Silva', reference: 'Patient/roberto-silva' },
      participant: [{ individual: { display: 'Dr. Jesús Robledo' } }],
      reasonCode: [{ text: 'Curación y retiro de puntos quirúrgicos' }],
      type: [{ text: 'Curación y Cirugía Menor' }]
    },
    {
      id: `seed-tue-6-${tue}`,
      date: tue,
      time: '21:00',
      period: { start: `${tue}T21:00:00`, end: `${tue}T21:30:00` },
      patientId: 'fernando-castro',
      patientName: 'Fernando Castro Ruiz',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Consulta nocturna de control glucémico',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 101',
      subject: { display: 'Fernando Castro Ruiz', reference: 'Patient/fernando-castro' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Consulta nocturna de control glucémico' }],
      type: [{ text: 'Consulta Nocturna' }]
    },

    // ==========================================
    // MIÉRCOLES
    // ==========================================
    {
      id: `seed-wed-1-${wed}`,
      date: wed,
      time: '08:00',
      period: { start: `${wed}T08:00:00`, end: `${wed}T08:30:00` },
      patientId: 'lucia-fernandez',
      patientName: 'Lucía Fernández Peña',
      practitionerName: 'Dra. Elena Torres Morales',
      practitionerSpecialty: 'Neumología',
      reason: 'Control de tos crónica y rinitis',
      status: 'in_room',
      statusLabel: 'En sala',
      room: 'Consultorio 105',
      subject: { display: 'Lucía Fernández Peña', reference: 'Patient/lucia-fernandez' },
      participant: [{ individual: { display: 'Dra. Elena Torres Morales' } }],
      reasonCode: [{ text: 'Control de tos crónica y rinitis' }],
      type: [{ text: 'Consulta Neumológica' }]
    },
    {
      id: `seed-wed-2-${wed}`,
      date: wed,
      time: '10:00',
      period: { start: `${wed}T10:00:00`, end: `${wed}T10:30:00` },
      patientId: 'carlos-mendoza',
      patientName: 'Carlos Mendoza Sánchez',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Revisión de radiografía de columna lumbar',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 103',
      subject: { display: 'Carlos Mendoza Sánchez', reference: 'Patient/carlos-mendoza' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Revisión de radiografía de columna lumbar' }],
      type: [{ text: 'Interpretación Radiológica' }]
    },
    {
      id: `seed-wed-3-${wed}`,
      date: wed,
      time: '12:30',
      period: { start: `${wed}T12:30:00`, end: `${wed}T13:00:00` },
      patientId: 'andrea-garza',
      patientName: 'Andrea Garza Delgado',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Examen general y laboratorios de rutina',
      status: 'finished',
      statusLabel: 'Finalizada',
      room: 'Consultorio 101',
      subject: { display: 'Andrea Garza Delgado', reference: 'Patient/andrea-garza' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Examen general y laboratorios de rutina' }],
      type: [{ text: 'Revisión Clínica' }]
    },
    {
      id: `seed-wed-4-${wed}`,
      date: wed,
      time: '15:30',
      period: { start: `${wed}T15:30:00`, end: `${wed}T16:00:00` },
      patientId: 'jorge-salazar',
      patientName: 'Jorge Eduardo Salazar',
      practitionerName: 'Lic. Carlos Treviño',
      practitionerSpecialty: 'Kinesiología Deportiva',
      reason: 'Terapia funcional para dolor de hombro',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Fisioterapia 1',
      subject: { display: 'Jorge Eduardo Salazar', reference: 'Patient/jorge-salazar' },
      participant: [{ individual: { display: 'Lic. Carlos Treviño' } }],
      reasonCode: [{ text: 'Terapia funcional para dolor de hombro' }],
      type: [{ text: 'Rehabilitación' }]
    },
    {
      id: `seed-wed-5-${wed}`,
      date: wed,
      time: '17:00',
      period: { start: `${wed}T17:00:00`, end: `${wed}T17:30:00` },
      patientId: 'valeria-morales',
      patientName: 'Valeria Morales Gómez',
      practitionerName: 'Dra. Beatriz Ramos',
      practitionerSpecialty: 'Cardiología Clínica',
      reason: 'Monitoreo Holter y control de presión arterial',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 104',
      subject: { display: 'Valeria Morales Gómez', reference: 'Patient/valeria-morales' },
      participant: [{ individual: { display: 'Dra. Beatriz Ramos' } }],
      reasonCode: [{ text: 'Monitoreo Holter y control de presión arterial' }],
      type: [{ text: 'Holter de Ritmo' }]
    },
    {
      id: `seed-wed-6-${wed}`,
      date: wed,
      time: '19:30',
      period: { start: `${wed}T19:30:00`, end: `${wed}T20:00:00` },
      patientId: 'ana-martinez',
      patientName: 'Ana Sofía Martínez',
      practitionerName: 'Lic. Sofía Mendiola',
      practitionerSpecialty: 'Fisioterapia y Rehabilitación',
      reason: 'Ejercicios de reeducación postural',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Bobath 2',
      subject: { display: 'Ana Sofía Martínez', reference: 'Patient/ana-martinez' },
      participant: [{ individual: { display: 'Lic. Sofía Mendiola' } }],
      reasonCode: [{ text: 'Ejercicios de reeducación postural' }],
      type: [{ text: 'Reeducación Postural' }]
    },

    // ==========================================
    // JUEVES
    // ==========================================
    {
      id: `seed-thu-1-${thu}`,
      date: thu,
      time: '09:30',
      period: { start: `${thu}T09:30:00`, end: `${thu}T10:00:00` },
      patientId: 'roberto-silva',
      patientName: 'Roberto Silva',
      practitionerName: 'Lic. Sofía Mendiola',
      practitionerSpecialty: 'Fisioterapia y Rehabilitación',
      reason: 'Fortalecimiento de cuádriceps post-cirugía',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Cabina Bobath 2',
      subject: { display: 'Roberto Silva', reference: 'Patient/roberto-silva' },
      participant: [{ individual: { display: 'Lic. Sofía Mendiola' } }],
      reasonCode: [{ text: 'Fortalecimiento de cuádriceps post-cirugía' }],
      type: [{ text: 'Fisioterapia Post-QX' }]
    },
    {
      id: `seed-thu-2-${thu}`,
      date: thu,
      time: '11:00',
      period: { start: `${thu}T11:00:00`, end: `${thu}T11:30:00` },
      patientId: 'mariana-silva',
      patientName: 'Mariana Silva Ruiz',
      practitionerName: 'Dra. Elena Torres Morales',
      practitionerSpecialty: 'Neumología',
      reason: 'Revisión de técnica de inhaladores',
      status: 'waiting',
      statusLabel: 'En espera',
      room: 'Consultorio 105',
      subject: { display: 'Mariana Silva Ruiz', reference: 'Patient/mariana-silva' },
      participant: [{ individual: { display: 'Dra. Elena Torres Morales' } }],
      reasonCode: [{ text: 'Revisión de técnica de inhaladores' }],
      type: [{ text: 'Educación Respiratoria' }]
    },
    {
      id: `seed-thu-2b-${thu}`,
      date: thu,
      time: '11:00',
      period: { start: `${thu}T11:00:00`, end: `${thu}T11:30:00` },
      patientId: 'roberto-silva',
      patientName: 'Roberto Silva',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Valoración ortopédica de rodilla post-QX',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 103',
      subject: { display: 'Roberto Silva', reference: 'Patient/roberto-silva' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Valoración ortopédica de rodilla post-QX' }],
      type: [{ text: 'Traumatología' }]
    },
    {
      id: `seed-thu-3-${thu}`,
      date: thu,
      time: '14:00',
      period: { start: `${thu}T14:00:00`, end: `${thu}T14:30:00` },
      patientId: 'patricia-luna',
      patientName: 'Patricia Luna Cruz',
      practitionerName: 'Dr. Jesús Robledo',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Chequeo metabólico y perfil lipídico',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 102',
      subject: { display: 'Patricia Luna Cruz', reference: 'Patient/patricia-luna' },
      participant: [{ individual: { display: 'Dr. Jesús Robledo' } }],
      reasonCode: [{ text: 'Chequeo metabólico y perfil lipídico' }],
      type: [{ text: 'Control Metabólico' }]
    },
    {
      id: `seed-thu-4-${thu}`,
      date: thu,
      time: '16:30',
      period: { start: `${thu}T16:30:00`, end: `${thu}T17:00:00` },
      patientId: 'miguel-torres',
      patientName: 'Miguel Ángel Torres',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Infiltración articular eco-guiada',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Quirófano Ambulatorio',
      subject: { display: 'Miguel Ángel Torres', reference: 'Patient/miguel-torres' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Infiltración articular eco-guiada' }],
      type: [{ text: 'Procedimiento Articular' }]
    },
    {
      id: `seed-thu-5-${thu}`,
      date: thu,
      time: '18:00',
      period: { start: `${thu}T18:00:00`, end: `${thu}T18:30:00` },
      patientId: 'fernando-castro',
      patientName: 'Fernando Castro Ruiz',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Seguimiento de síndrome metabólico',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 101',
      subject: { display: 'Fernando Castro Ruiz', reference: 'Patient/fernando-castro' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Seguimiento de síndrome metabólico' }],
      type: [{ text: 'Consulta Médica' }]
    },
    {
      id: `seed-thu-6-${thu}`,
      date: thu,
      time: '20:30',
      period: { start: `${thu}T20:30:00`, end: `${thu}T21:00:00` },
      patientId: 'andrea-garza',
      patientName: 'Andrea Garza Delgado',
      practitionerName: 'Lic. Carlos Treviño',
      practitionerSpecialty: 'Kinesiología Deportiva',
      reason: 'Terapia manual para contractura dorsal',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Fisioterapia 1',
      subject: { display: 'Andrea Garza Delgado', reference: 'Patient/andrea-garza' },
      participant: [{ individual: { display: 'Lic. Carlos Treviño' } }],
      reasonCode: [{ text: 'Terapia manual para contractura dorsal' }],
      type: [{ text: 'Kinesiología' }]
    },

    // ==========================================
    // VIERNES
    // ==========================================
    {
      id: `seed-fri-1-${fri}`,
      date: fri,
      time: '08:30',
      period: { start: `${fri}T08:30:00`, end: `${fri}T09:00:00` },
      patientId: 'carlos-mendoza',
      patientName: 'Carlos Mendoza Sánchez',
      practitionerName: 'Dra. Beatriz Ramos',
      practitionerSpecialty: 'Cardiología Clínica',
      reason: 'Prueba de esfuerzo y valoración pre-quirúrgica',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 104',
      subject: { display: 'Carlos Mendoza Sánchez', reference: 'Patient/carlos-mendoza' },
      participant: [{ individual: { display: 'Dra. Beatriz Ramos' } }],
      reasonCode: [{ text: 'Prueba de esfuerzo y valoración pre-quirúrgica' }],
      type: [{ text: 'Cardiología' }]
    },
    {
      id: `seed-fri-2-${fri}`,
      date: fri,
      time: '10:30',
      period: { start: `${fri}T10:30:00`, end: `${fri}T11:00:00` },
      patientId: 'lucia-fernandez',
      patientName: 'Lucía Fernández Peña',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Consulta de medicina preventiva',
      status: 'finished',
      statusLabel: 'Finalizada',
      room: 'Consultorio 101',
      subject: { display: 'Lucía Fernández Peña', reference: 'Patient/lucia-fernandez' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Consulta de medicina preventiva' }],
      type: [{ text: 'Medicina General' }]
    },
    {
      id: `seed-fri-3-${fri}`,
      date: fri,
      time: '12:00',
      period: { start: `${fri}T12:00:00`, end: `${fri}T12:30:00` },
      patientId: 'jorge-salazar',
      patientName: 'Jorge Eduardo Salazar',
      practitionerName: 'Dra. Elena Torres Morales',
      practitionerSpecialty: 'Neumología',
      reason: 'Evaluación de apnea obstructiva del sueño',
      status: 'waiting',
      statusLabel: 'En espera',
      room: 'Consultorio 105',
      subject: { display: 'Jorge Eduardo Salazar', reference: 'Patient/jorge-salazar' },
      participant: [{ individual: { display: 'Dra. Elena Torres Morales' } }],
      reasonCode: [{ text: 'Evaluación de apnea obstructiva del sueño' }],
      type: [{ text: 'Estudio Neumológico' }]
    },
    {
      id: `seed-fri-4-${fri}`,
      date: fri,
      time: '15:00',
      period: { start: `${fri}T15:00:00`, end: `${fri}T15:30:00` },
      patientId: 'valeria-morales',
      patientName: 'Valeria Morales Gómez',
      practitionerName: 'Dr. Jesús Robledo',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Control de diabetes y ajuste de esquema',
      status: 'in_consultation',
      statusLabel: 'En consulta',
      room: 'Consultorio 102',
      subject: { display: 'Valeria Morales Gómez', reference: 'Patient/valeria-morales' },
      participant: [{ individual: { display: 'Dr. Jesús Robledo' } }],
      reasonCode: [{ text: 'Control de diabetes y ajuste de esquema' }],
      type: [{ text: 'Control Metabólico' }]
    },
    {
      id: `seed-fri-4b-${fri}`,
      date: fri,
      time: '15:00',
      period: { start: `${fri}T15:00:00`, end: `${fri}T15:30:00` },
      patientId: 'fernando-castro',
      patientName: 'Fernando Castro Ruiz',
      practitionerName: 'Dra. Beatriz Ramos',
      practitionerSpecialty: 'Cardiología Clínica',
      reason: 'Evaluación cardiológica vespertina',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 104',
      subject: { display: 'Fernando Castro Ruiz', reference: 'Patient/fernando-castro' },
      participant: [{ individual: { display: 'Dra. Beatriz Ramos' } }],
      reasonCode: [{ text: 'Evaluación cardiológica vespertina' }],
      type: [{ text: 'Cardiología' }]
    },
    {
      id: `seed-fri-5-${fri}`,
      date: fri,
      time: '17:30',
      period: { start: `${fri}T17:30:00`, end: `${fri}T18:00:00` },
      patientId: 'ana-martinez',
      patientName: 'Ana Sofía Martínez',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Seguimiento de esguince de tobillo grado II',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 103',
      subject: { display: 'Ana Sofía Martínez', reference: 'Patient/ana-martinez' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Seguimiento de esguince de tobillo grado II' }],
      type: [{ text: 'Traumatología' }]
    },
    {
      id: `seed-fri-6-${fri}`,
      date: fri,
      time: '19:00',
      period: { start: `${fri}T19:00:00`, end: `${fri}T19:30:00` },
      patientId: 'roberto-silva',
      patientName: 'Roberto Silva',
      practitionerName: 'Lic. Carlos Treviño',
      practitionerSpecialty: 'Kinesiología Deportiva',
      reason: 'Masoterapia descontracturante lumbar',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Fisioterapia 1',
      subject: { display: 'Roberto Silva', reference: 'Patient/roberto-silva' },
      participant: [{ individual: { display: 'Lic. Carlos Treviño' } }],
      reasonCode: [{ text: 'Masoterapia descontracturante lumbar' }],
      type: [{ text: 'Fisioterapia' }]
    },
    {
      id: `seed-fri-7-${fri}`,
      date: fri,
      time: '21:30',
      period: { start: `${fri}T21:30:00`, end: `${fri}T22:00:00` },
      patientId: 'patricia-luna',
      patientName: 'Patricia Luna Cruz',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Consulta nocturna de ajuste antihipertensivo',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 101',
      subject: { display: 'Patricia Luna Cruz', reference: 'Patient/patricia-luna' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Consulta nocturna de ajuste antihipertensivo' }],
      type: [{ text: 'Medicina Interna' }]
    },

    // ==========================================
    // SÁBADO
    // ==========================================
    {
      id: `seed-sat-1-${sat}`,
      date: sat,
      time: '09:00',
      period: { start: `${sat}T09:00:00`, end: `${sat}T09:30:00` },
      patientId: 'andrea-garza',
      patientName: 'Andrea Garza Delgado',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Chequeo preventivo de fin de semana',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 101',
      subject: { display: 'Andrea Garza Delgado', reference: 'Patient/andrea-garza' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Chequeo preventivo de fin de semana' }],
      type: [{ text: 'Medicina General' }]
    },
    {
      id: `seed-sat-2-${sat}`,
      date: sat,
      time: '10:30',
      period: { start: `${sat}T10:30:00`, end: `${sat}T11:00:00` },
      patientId: 'miguel-torres',
      patientName: 'Miguel Ángel Torres',
      practitionerName: 'Lic. Sofía Mendiola',
      practitionerSpecialty: 'Fisioterapia y Rehabilitación',
      reason: 'Terapia física de movilidad articular',
      status: 'in_room',
      statusLabel: 'En sala',
      room: 'Cabina Bobath 2',
      subject: { display: 'Miguel Ángel Torres', reference: 'Patient/miguel-torres' },
      participant: [{ individual: { display: 'Lic. Sofía Mendiola' } }],
      reasonCode: [{ text: 'Terapia física de movilidad articular' }],
      type: [{ text: 'Fisioterapia' }]
    },
    {
      id: `seed-sat-3-${sat}`,
      date: sat,
      time: '12:00',
      period: { start: `${sat}T12:00:00`, end: `${sat}T12:30:00` },
      patientId: 'fernando-castro',
      patientName: 'Fernando Castro Ruiz',
      practitionerName: 'Dra. Beatriz Ramos',
      practitionerSpecialty: 'Cardiología Clínica',
      reason: 'Consulta de hipertensión resistente',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 104',
      subject: { display: 'Fernando Castro Ruiz', reference: 'Patient/fernando-castro' },
      participant: [{ individual: { display: 'Dra. Beatriz Ramos' } }],
      reasonCode: [{ text: 'Consulta de hipertensión resistente' }],
      type: [{ text: 'Cardiología' }]
    },
    {
      id: `seed-sat-4-${sat}`,
      date: sat,
      time: '14:30',
      period: { start: `${sat}T14:30:00`, end: `${sat}T15:00:00` },
      patientId: 'carlos-mendoza',
      patientName: 'Carlos Mendoza Sánchez',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Valoración traumatológica de rodilla',
      status: 'waiting',
      statusLabel: 'En espera',
      room: 'Consultorio 103',
      subject: { display: 'Carlos Mendoza Sánchez', reference: 'Patient/carlos-mendoza' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Valoración traumatológica de rodilla' }],
      type: [{ text: 'Traumatología' }]
    },
    {
      id: `seed-sat-5-${sat}`,
      date: sat,
      time: '16:00',
      period: { start: `${sat}T16:00:00`, end: `${sat}T16:30:00` },
      patientId: 'mariana-silva',
      patientName: 'Mariana Silva Ruiz',
      practitionerName: 'Dr. Jesús Robledo',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Renovación de receta de Losartán y laboratorios',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 102',
      subject: { display: 'Mariana Silva Ruiz', reference: 'Patient/mariana-silva' },
      participant: [{ individual: { display: 'Dr. Jesús Robledo' } }],
      reasonCode: [{ text: 'Renovación de receta de Losartán y laboratorios' }],
      type: [{ text: 'Control Trimestral' }]
    },
    {
      id: `seed-sat-6-${sat}`,
      date: sat,
      time: '18:00',
      period: { start: `${sat}T18:00:00`, end: `${sat}T18:30:00` },
      patientId: 'lucia-fernandez',
      patientName: 'Lucía Fernández Peña',
      practitionerName: 'Lic. Carlos Treviño',
      practitionerSpecialty: 'Kinesiología Deportiva',
      reason: 'Kinesiología y estiramientos terapéuticos',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Fisioterapia 1',
      subject: { display: 'Lucía Fernández Peña', reference: 'Patient/lucia-fernandez' },
      participant: [{ individual: { display: 'Lic. Carlos Treviño' } }],
      reasonCode: [{ text: 'Kinesiología y estiramientos terapéuticos' }],
      type: [{ text: 'Kinesiología' }]
    },

    // ==========================================
    // DOMINGO
    // ==========================================
    {
      id: `seed-sun-1-${sun}`,
      date: sun,
      time: '09:30',
      period: { start: `${sun}T09:30:00`, end: `${sun}T10:00:00` },
      patientId: 'jorge-salazar',
      patientName: 'Jorge Eduardo Salazar',
      practitionerName: 'Dr. Alejandro Morales',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Consulta dominical de control general',
      status: 'confirmed',
      statusLabel: 'Confirmada',
      room: 'Consultorio 101',
      subject: { display: 'Jorge Eduardo Salazar', reference: 'Patient/jorge-salazar' },
      participant: [{ individual: { display: 'Dr. Alejandro Morales' } }],
      reasonCode: [{ text: 'Consulta dominical de control general' }],
      type: [{ text: 'Medicina General' }]
    },
    {
      id: `seed-sun-2-${sun}`,
      date: sun,
      time: '11:00',
      period: { start: `${sun}T11:00:00`, end: `${sun}T11:30:00` },
      patientId: 'valeria-morales',
      patientName: 'Valeria Morales Gómez',
      practitionerName: 'Lic. Sofía Mendiola',
      practitionerSpecialty: 'Fisioterapia y Rehabilitación',
      reason: 'Terapia motriz y relajación miofascial',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Bobath 2',
      subject: { display: 'Valeria Morales Gómez', reference: 'Patient/valeria-morales' },
      participant: [{ individual: { display: 'Lic. Sofía Mendiola' } }],
      reasonCode: [{ text: 'Terapia motriz y relajación miofascial' }],
      type: [{ text: 'Fisioterapia' }]
    },
    {
      id: `seed-sun-3-${sun}`,
      date: sun,
      time: '13:30',
      period: { start: `${sun}T13:30:00`, end: `${sun}T14:00:00` },
      patientId: 'ana-martinez',
      patientName: 'Ana Sofía Martínez',
      practitionerName: 'Dr. Jesús Robledo',
      practitionerSpecialty: 'Medicina Interna',
      reason: 'Evaluación médica preventiva y signos vitales',
      status: 'waiting',
      statusLabel: 'En espera',
      room: 'Consultorio 102',
      subject: { display: 'Ana Sofía Martínez', reference: 'Patient/ana-martinez' },
      participant: [{ individual: { display: 'Dr. Jesús Robledo' } }],
      reasonCode: [{ text: 'Evaluación médica preventiva y signos vitales' }],
      type: [{ text: 'Medicina Preventiva' }]
    },
    {
      id: `seed-sun-4-${sun}`,
      date: sun,
      time: '17:00',
      period: { start: `${sun}T17:00:00`, end: `${sun}T17:30:00` },
      patientId: 'fernando-castro',
      patientName: 'Fernando Castro Ruiz',
      practitionerName: 'Dr. Marcos Rivas',
      practitionerSpecialty: 'Ortopedia y Traumatología',
      reason: 'Consulta de urgencias menores por contusión',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Consultorio 103',
      subject: { display: 'Fernando Castro Ruiz', reference: 'Patient/fernando-castro' },
      participant: [{ individual: { display: 'Dr. Marcos Rivas' } }],
      reasonCode: [{ text: 'Consulta de urgencias menores por contusión' }],
      type: [{ text: 'Traumatología' }]
    },
    {
      id: `seed-sun-5-${sun}`,
      date: sun,
      time: '19:30',
      period: { start: `${sun}T19:30:00`, end: `${sun}T20:00:00` },
      patientId: 'miguel-torres',
      patientName: 'Miguel Ángel Torres',
      practitionerName: 'Lic. Carlos Treviño',
      practitionerSpecialty: 'Kinesiología Deportiva',
      reason: 'Recuperación deportiva y crioterapia',
      status: 'planned',
      statusLabel: 'Programada',
      room: 'Cabina Fisioterapia 1',
      subject: { display: 'Miguel Ángel Torres', reference: 'Patient/miguel-torres' },
      participant: [{ individual: { display: 'Lic. Carlos Treviño' } }],
      reasonCode: [{ text: 'Recuperación deportiva y crioterapia' }],
      type: [{ text: 'Kinesiología' }]
    }
  ];
}
